FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN mkdir -p setup data

RUN apt-get update && apt-get install -y sqlite3 && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

CMD ["python", "src/main.py"]